# Generated by Django 4.2.6 on 2023-10-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteresseCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=150)),
                ('mensagem', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'interesse_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InteresseVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=150)),
                ('mensagem', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'interesse_venda',
                'managed': False,
            },
        ),
    ]
