# Generated by Django 4.2.6 on 2023-10-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_interessecompra_interessevenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicaoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicao_novo', models.BooleanField()),
                ('ano', models.PositiveSmallIntegerField()),
                ('cor', models.CharField(max_length=50)),
                ('quilometragem', models.IntegerField()),
                ('leiloado', models.BooleanField()),
            ],
            options={
                'db_table': 'condicoes_veiculos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'marcas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'modelos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagamento', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'veiculos',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CondicoesVeiculos',
        ),
        migrations.DeleteModel(
            name='Marcas',
        ),
        migrations.DeleteModel(
            name='Modelos',
        ),
        migrations.DeleteModel(
            name='Veiculos',
        ),
    ]
